logs:
  configs:
    - name: default
      clients:
        - url: http://localhost:3100/loki/api/v1/push
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: system
          static_configs:
            - targets: [localhost]
              labels:
                job: syslog
                __path__: /var/log/syslog
