<?php

/**
 * @file
 * OpenTelemetry Example install hooks.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function observability_example_install($phase) {
  // Opening metrics to any user.
  user_role_grant_permissions(RoleInterface::ANONYMOUS_ID, ['access prometheus metrics']);
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, ['access prometheus metrics']);
}
