{
 "title": "Observability dasboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Traces: last 20 items",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "limit": 20 }
   ]
  },
  {
   "title": "Syslog logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"syslog\"}"
    }
   ]
  },
  {
   "title": "Nginx logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"nginx\"}"
    }
   ]
  },
  {
   "title": "Node count by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "drupal_node_count_total" }
   ]
  }
 ]
}